on: [pull_request]

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read


jobs:
  test-python:
    uses: NERC-CEH/dri-cicd/.github/workflows/test-python.yml@main
    with:
      use_uv: true

  build-test-deploy-docker:
    needs: [test-python]
    uses: NERC-CEH/dri-cicd/.github/workflows/build-test-deploy-docker.yml@main
    with:
      use_uv: true
      package_name: mypackage
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
